Repository sailaja-adapa/Vipreshana, pull requests merged in 2025-07, with the labels that each got.

#200 UI & Bug Fix
  src/Registration.jsx
  src/bbg.jpg
  src/components/Footer.js
  src/login.jsx
Labels: SSOC S4, Intermediate

#223 Added the markdown github action file
  .github/workflows/issue-welcome.yml
Labels: SSOC S4, Beginner

#258 fixed collison of navbar and user logo icon
  src/LoginDashboard.jsx
  src/components/Navbar.jsx
Labels: SSoC25, Beginner
