Repository sailaja-adapa/Vipreshana, pull requests merged in 2025-06, with the labels that each got.

#28 feat(theme): add global dark/light mode toggle across all UI pages
  package-lock.json
  package.json
  src/AdminDashboard.jsx
  src/App.js
  src/Bookings.jsx
  src/Dashboard.jsx
  src/ForgotPassword.jsx
  src/Location.jsx
  src/LoginDashboard.jsx
  src/Registration.jsx
  src/ResetPassword.jsx
  src/components/Driver.jsx
  src/components/User.jsx
  src/context/ThemeContext.jsx
  src/login.jsx
Labels: SSOC S4, Advanced

#81 FIX #76: Addition of animated how it works page
  package-lock.json
  package.json
  src/App.js
  src/Dashboard.jsx
  src/Howitworks.jsx
Labels: SSOC S4, Advanced

#153 Fix: Invalid URL error handling
  server/server.js
  src/App.js
  src/NotFound.jsx
Labels: SSOC S4, Intermediate

#154 FIX #145: dark mode fixed in registration page
  src/Registration.jsx
Labels: SSOC S4, Intermediate

#192 404 implementation completed [#191 Resolved]
  .vscode/settings.json
  package-lock.json
  package.json
  src/NotFound.jsx
Labels: SSOC S4, Advanced

#194 Added Table of Contents and LICENSE
  README.md
Labels: SSOC S4, Beginner
